[metadata]
name = "nu-history"
description = "A channel to select from your nu history"

[source]
command = "nu -c 'open ~/.config/nushell/history.sqlite3 | query db \"SELECT DISTINCT command_line FROM history ORDER BY id DESC\" | get command_line | each { |x| $x + (char nul) } | str join'"
entry_delimiter = "\u0000"
